language: csharp
sudo: required
dist: xenial
mono: none
dotnet: 2.2.103
install:
- dotnet restore
cache:
  directories:
    - node_modules
script:
- dotnet build
- dotnet test IdentityIssuer.WebAPI.UnitTests/IdentityIssuer.WebAPI.UnitTests.csproj
- dotnet test IdentityIssuer.Infrastructure.UnitTests/IdentityIssuer.Infrastructure.UnitTests.csproj
- dotnet test IdentityIssuer.Application.UnitTests/IdentityIssuer.Application.UnitTests.csproj