language: csharp
sudo: required
dist: xenial
mono: none
dotnet: 5.0
install:
- dotnet restore
cache:
  directories:
    - node_modules
script:
- dotnet build
- dotnet test Src/Tests/IdentityIssuer.WebAPI.UnitTests/IdentityIssuer.WebAPI.UnitTests.csproj
- dotnet test Src/Tests/IdentityIssuer.Infrastructure.UnitTests/IdentityIssuer.Infrastructure.UnitTests.csproj
- dotnet test Src/Tests/IdentityIssuer.Application.UnitTests/IdentityIssuer.Application.UnitTests.csproj
